### YamlMime:UniversalReference
items:
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode:enum'
    summary: |-
      Коды ошибок для пользовательских функций. Коды ошибок будут отображаться в ячейке, вызвавшей функцию.

      В дополнение к этим кодам ошибок отображаются настраиваемые сообщения об ошибках. Настраиваемые сообщения отображаются в меню индикации ошибки, доступ к которому осуществляется при наведении курсора на флаг ошибки в каждой ячейке с ошибкой.
    name: CustomFunctions.ErrorCode
    fullName: CustomFunctions.ErrorCode
    langs:
      - typeScript
    type: enum
    package: custom-functions-runtime!
    children:
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member'
    summary: 'Этот код ошибки указывает на то, что используемая функция делится на ноль или пустые ячейки. Настраиваемое сообщение об ошибке не может быть использовано. \[[Набор API: кустомфунктионсрунтиме 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: divisionByZero
    fullName: divisionByZero
    langs:
      - typeScript
    type: field
    numericValue: '"#DIV/0!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member'
    summary: 'Этот код ошибки указывает на наличие опечатки в имени функции. Обратите внимание, что этот код ошибки поддерживается как ошибка ввода пользовательской функции, но не в качестве ошибки вывода пользовательской функции. Настраиваемое сообщение об ошибке не может быть использовано. \[[Набор API: кустомфунктионсрунтиме 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidName
    fullName: invalidName
    langs:
      - typeScript
    type: field
    numericValue: '"#NAME?"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member'
    summary: 'Этот код ошибки указывает на наличие проблемы с числом в функции. Настраиваемое сообщение об ошибке не может быть использовано. \[[Набор API: кустомфунктионсрунтиме 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidNumber
    fullName: invalidNumber
    langs:
      - typeScript
    type: field
    numericValue: '"#NUM!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member'
    summary: 'Этот код ошибки указывает на то, что функция ссылается на недопустимую ячейку. Обратите внимание, что этот код ошибки поддерживается как ошибка ввода пользовательской функции, но не в качестве ошибки вывода пользовательской функции. Настраиваемое сообщение об ошибке не может быть использовано. \[[Набор API: кустомфунктионсрунтиме 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidReference
    fullName: invalidReference
    langs:
      - typeScript
    type: field
    numericValue: '"#REF!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member'
    summary: 'Этот код ошибки указывает на то, что значение в функции имеет неверный тип данных. При необходимости можно использовать настраиваемое сообщение об ошибке в дополнение к коду ошибки. \[[Набор API: кустомфунктионсрунтиме 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidValue
    fullName: invalidValue
    langs:
      - typeScript
    type: field
    numericValue: '"#VALUE!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member'
    summary: 'Этот код ошибки указывает на то, что функция или служба недоступна. При необходимости можно использовать настраиваемое сообщение об ошибке в дополнение к коду ошибки. \[[Набор API: кустомфунктионсрунтиме 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: notAvailable
    fullName: notAvailable
    langs:
      - typeScript
    type: field
    numericValue: '"#N/A"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member'
    summary: 'Этот код ошибки указывает на то, что диапазоны функции не пересекаются. Настраиваемое сообщение об ошибке не может быть использовано. \[[Набор API: кустомфунктионсрунтиме 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: nullReference
    fullName: nullReference
    langs:
      - typeScript
    type: field
    numericValue: '"#NULL!"'